---
- name: Install trac package.
  apt: name="{{item}}" state=latest update_cache=yes
  with_items: "{{trac_packages}}"

- name: Create trac user
  user: name=trac comment="Trac package tracker" createhome=no
        shell=/usr/sbin/nologin system=yes
